apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wisdompetmedicine-petaggregator-api-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /petaggregator
        pathType: Prefix
        backend:
          service:
            name: petaggregator
            port:
              number: 80