kubectl apply -f wisdom-configstore.yaml
kubectl apply -f wisdom-conversation.yaml
kubectl apply -f wisdom-crypto.yaml
kubectl apply -f wisdom-inputbinding.yaml
kubectl apply -f wisdom-lock.yaml
kubectl apply -f wisdom-outputbinding.yaml
kubectl apply -f wisdom-pubsub.yaml
kubectl apply -f wisdom-resiliency.yaml
kubectl apply -f wisdom-secretstore-vault.yaml
kubectl apply -f wisdom-statestore.yaml
kubectl apply -f wisdom-workflowstore.yaml