apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: petoutputbinding
spec:
  type: bindings.azure.storagequeues
  version: v1
  metadata:
  - name: accountName
    value: "wisdompetmed"
  - name: accountKey
    secretKeyRef:
      name: azurestorage
      key: azurestorage
  - name: queueName
    value: "admittedqueue"
  - name: ttlInSeconds
    value: "60"
auth:
  secretStore: wisdomsecretstore