apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: wisdomresiliency
spec:
  policies:
    retries:
      wpm-service-retry-forever:
        policy: exponential
        maxInterval: 10s
        maxRetries: -1
      wpm-service-retry:
        policy: exponential
        maxInterval: 10s
        maxRetries: 5
    timeouts:
      wpm-service-timeout: 10s
    circuitBreakers:
      wpm-service-cb:
        interval: 5s
        trip: consecutiveFailures > 10

  targets:
    apps:
      pet:
        retry: wpm-service-retry
      rescuequery:
        timeout: wpm-service-timeout
      hospital:
        retry: wpm-service-retry
        circuitBreaker: wpm-service-cb