apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: wisdomsecretstore
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
    - name: secretsfile
      value: d:/secrets.json
    - name: nestedSeparator
      value: ":"
