<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
	<ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
	<NoWarn>CS0618</NoWarn>
	<UserSecretsId>e5e94f63-4206-45b5-a09f-91dbcee85b57</UserSecretsId>
	<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	<DockerComposeProjectPath>..\docker-compose.dcproj</DockerComposeProjectPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
	<PackageReference Include="Dapr.AspNetCore" Version="1.15.4" />
    <PackageReference Include="Dapr.Extensions.Configuration" Version="1.15.4" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.0.2" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />
  </ItemGroup>

</Project>